// backend/src/modules/audit/audit.actions.js

// ============================================
// AUDIT ACTIONS — IMMUTABLE BUSINESS FACTS
// ============================================
//
// ⚠️  LOCKED — DO NOT RENAME OR REMOVE
// ⚠️  Adding new actions is allowed
// ⚠️  Each action represents an irreversible business event
//
// Metadata examples are GUIDELINES, not enforced schemas.
// ============================================

export const AuditAction = Object.freeze({
  // ============================================
  // SHOP / ACCOUNT LIFECYCLE
  // ============================================
  SHOP_ACCOUNT_CREATED: "SHOP_ACCOUNT_CREATED",
  SHOP_SETUP_COMPLETED: "SHOP_SETUP_COMPLETED",
  SHOP_ACTIVATED: "SHOP_ACTIVATED",
  SHOP_SUSPENDED: "SHOP_SUSPENDED",
  SHOP_SUSPENDED_DUE_TO_NON_PAYMENT: "SHOP_SUSPENDED_DUE_TO_NON_PAYMENT",
  SHOP_DETAILS_UPDATED: "SHOP_DETAILS_UPDATED",
  SHOP_PLAN_ASSIGNED_BY_ADMIN: "SHOP_PLAN_ASSIGNED_BY_ADMIN",

  // ============================================
  // USERS (ERP + ADMIN ACTIONS)
  // ============================================
  USER_CREATED: "USER_CREATED",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_PROFILE_UPDATED_BY_ADMIN: "USER_PROFILE_UPDATED_BY_ADMIN",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_ROLE_CHANGED_BY_ADMIN: "USER_ROLE_CHANGED_BY_ADMIN",
  USER_BRANCH_CHANGED: "USER_BRANCH_CHANGED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_REACTIVATED: "USER_REACTIVATED",
  USER_ACTIVATED_BY_ADMIN: "USER_ACTIVATED_BY_ADMIN",
  USER_SUSPENDED_BY_ADMIN: "USER_SUSPENDED_BY_ADMIN",
  USER_DELETED_BY_ADMIN: "USER_DELETED_BY_ADMIN",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  USER_PASSWORD_RESET_BY_ADMIN: "USER_PASSWORD_RESET_BY_ADMIN",
  USER_EMAIL_CHANGED: "USER_EMAIL_CHANGED",
  USER_PHONE_CHANGED: "USER_PHONE_CHANGED",

  // ============================================
  // BRANCHES
  // ============================================
  BRANCH_CREATED: "BRANCH_CREATED",
  BRANCH_RENAMED: "BRANCH_RENAMED",
  BRANCH_DEACTIVATED: "BRANCH_DEACTIVATED",
  BRANCH_REACTIVATED: "BRANCH_REACTIVATED",

  // ============================================
  // SUBSCRIPTIONS / BILLING
  // ============================================
  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_CREATED_PENDING_PAYMENT: "SUBSCRIPTION_CREATED_PENDING_PAYMENT",
  SUBSCRIPTION_ACTIVATED: "SUBSCRIPTION_ACTIVATED",
  SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
  PLAN_UPGRADED: "PLAN_UPGRADED",
  PLAN_DOWNGRADED: "PLAN_DOWNGRADED",
  SUBSCRIPTION_ENTERED_GRACE: "SUBSCRIPTION_ENTERED_GRACE",
  PAYMENT_MARKED_OVERDUE: "PAYMENT_MARKED_OVERDUE",
  USERS_DISABLED_DUE_TO_PLAN_DOWNGRADE: "USERS_DISABLED_DUE_TO_PLAN_DOWNGRADE",
  BRANCHES_DEACTIVATED_DUE_TO_PLAN_DOWNGRADE:
    "BRANCHES_DEACTIVATED_DUE_TO_PLAN_DOWNGRADE",

  // ============================================
  // PLANS (CADMIN)
  // ============================================
  PLAN_CREATED: "PLAN_CREATED",
  PLAN_UPDATED: "PLAN_UPDATED",
  PLAN_ACTIVATED: "PLAN_ACTIVATED",
  PLAN_SUSPENDED: "PLAN_SUSPENDED",
  PLAN_REACTIVATED: "PLAN_REACTIVATED",
  PLAN_CLONED: "PLAN_CLONED",
  PLAN_DELETED: "PLAN_DELETED",
  PLAN_AUTO_SUSPENDED_BY_CRON: "PLAN_AUTO_SUSPENDED_BY_CRON",

  // ============================================
  // DOCUMENTS / VERIFICATION
  // ============================================
  SHOP_DOCUMENT_UPLOADED: "SHOP_DOCUMENT_UPLOADED",
  SHOP_DOCUMENT_RESUBMITTED: "SHOP_DOCUMENT_RESUBMITTED",
  SHOP_DOCUMENT_UPLOADED_BY_ADMIN: "SHOP_DOCUMENT_UPLOADED_BY_ADMIN",
  SHOP_DOCUMENT_REPLACED_BY_ADMIN: "SHOP_DOCUMENT_REPLACED_BY_ADMIN",
  SHOP_VERIFICATION_FILE_VERIFIED: "SHOP_VERIFICATION_FILE_VERIFIED",
  SHOP_VERIFICATION_FILE_REJECTED: "SHOP_VERIFICATION_FILE_REJECTED",
  SHOP_VERIFICATION_FILE_BATCH_VERIFIED:
    "SHOP_VERIFICATION_FILE_BATCH_VERIFIED",
  SHOP_VERIFICATION_FILE_BATCH_REJECTED:
    "SHOP_VERIFICATION_FILE_BATCH_REJECTED",
  SHOP_VERIFICATION_COMPLETED: "SHOP_VERIFICATION_COMPLETED",
  SHOP_VERIFICATION_PARTIALLY_REJECTED: "SHOP_VERIFICATION_PARTIALLY_REJECTED",
  SHOP_VERIFICATION_REJECTED: "SHOP_VERIFICATION_REJECTED",

  // ============================================
  // TICKETS / SUPPORT
  // ============================================
  TICKET_CREATED: "TICKET_CREATED",
  TICKET_CANCELLED: "TICKET_CANCELLED",
  TICKET_REOPENED: "TICKET_REOPENED",
  TICKET_STATUS_UPDATED_BY_ADMIN: "TICKET_STATUS_UPDATED_BY_ADMIN",
  TICKET_RESOLVED_BY_ADMIN: "TICKET_RESOLVED_BY_ADMIN",
  TICKET_CLOSED_BY_ADMIN: "TICKET_CLOSED_BY_ADMIN",
  ENQUIRY_REPLIED: "ENQUIRY_REPLIED",
  ENQUIRY_STATUS_CHANGED: "ENQUIRY_STATUS_CHANGED",

  // ============================================
  // CADMIN (INTERNAL ADMINS)
  // ============================================
  CADMIN_CREATED: "CADMIN_CREATED",
  CADMIN_PROFILE_UPDATED: "CADMIN_PROFILE_UPDATED",
  CADMIN_ROLE_CHANGED: "CADMIN_ROLE_CHANGED",
  CADMIN_ACTIVATED: "CADMIN_ACTIVATED",
  CADMIN_SUSPENDED: "CADMIN_SUSPENDED",
  CADMIN_PASSWORD_RESET_COMPLETED: "CADMIN_PASSWORD_RESET_COMPLETED",
  CADMIN_LOGIN_SUCCESS: "CADMIN_LOGIN_SUCCESS",
  CADMIN_LOGOUT: "CADMIN_LOGOUT",

  // ============================================
  // SYSTEM / AUTOMATION
  // ============================================
  SYSTEM_BROADCAST_CREATED: "SYSTEM_BROADCAST_CREATED",
  BROADCAST_CREATED: "BROADCAST_CREATED",
  BROADCAST_SENT: "BROADCAST_SENT",
  BROADCAST_SCHEDULED: "BROADCAST_SCHEDULED",
  BROADCAST_CANCELLED: "BROADCAST_CANCELLED",
  SYSTEM_BROADCAST_SENT: "SYSTEM_BROADCAST_SENT",
  SYSTEM_BROADCAST_FAILED: "SYSTEM_BROADCAST_FAILED",
  SYSTEM_MAINTENANCE_ENABLED: "SYSTEM_MAINTENANCE_ENABLED",
  SYSTEM_MAINTENANCE_DISABLED: "SYSTEM_MAINTENANCE_DISABLED",

  // ============================================
  // PURCHASE MODULE ACTIONS
  // ============================================
  PURCHASE_INVOICE_CREATED: "PURCHASE_INVOICE_CREATED",
  PURCHASE_INVOICE_UPDATED: "PURCHASE_INVOICE_UPDATED",
  PURCHASE_INVOICE_CONFIRMED: "PURCHASE_INVOICE_CONFIRMED",
  PURCHASE_INVOICE_CONFIRMED_EDITED: "PURCHASE_INVOICE_CONFIRMED_EDITED",
  PURCHASE_INVOICE_CANCELLED: "PURCHASE_INVOICE_CANCELLED",
  PURCHASE_PAYMENT_CREATED: "PURCHASE_PAYMENT_CREATED",
  PURCHASE_PAYMENT_STATUS_UPDATED: "PURCHASE_PAYMENT_STATUS_UPDATED",
  PURCHASE_PAYMENT_RECORDED: "PURCHASE_PAYMENT_RECORDED",
  PURCHASE_RETURN_CREATED: "PURCHASE_RETURN_CREATED",
  PURCHASE_RETURN_APPROVED: "PURCHASE_RETURN_APPROVED",
  PURCHASE_RETURN_REJECTED: "PURCHASE_RETURN_REJECTED",
  PURCHASE_RETURN_CANCELLED: "PURCHASE_RETURN_CANCELLED",
  PURCHASE_RETURN_REVERTED: "PURCHASE_RETURN_REVERTED",
  CREDIT_NOTE_CREATED: "CREDIT_NOTE_CREATED",
  CREDIT_NOTE_APPLIED: "CREDIT_NOTE_APPLIED",
  CREDIT_NOTE_EXPIRED: "CREDIT_NOTE_EXPIRED",

  // ============================================
  //  SALES MODULE ACTIONS (ADDED)
  // ============================================
  SALES_INVOICE_CREATED: "SALES_INVOICE_CREATED",
  SALES_INVOICE_UPDATED: "SALES_INVOICE_UPDATED",
  SALES_INVOICE_EDITED_SUPER_ADMIN: "SALES_INVOICE_EDITED_SUPER_ADMIN",
  SALES_INVOICE_CONFIRMED: "SALES_INVOICE_CONFIRMED",
  SALES_INVOICE_CANCELLED: "SALES_INVOICE_CANCELLED",
  SALES_INVOICE_PARKED: "SALES_INVOICE_PARKED",
  SALES_INVOICE_RESUMED: "SALES_INVOICE_RESUMED",
  SALES_PAYMENT_RECORDED: "SALES_PAYMENT_RECORDED",
  SALES_RETURN_CREATED: "SALES_RETURN_CREATED",
  SALES_RETURN_CANCELLED: "SALES_RETURN_CANCELLED",
  SALES_PAYMENT_STATUS_UPDATED: "SALES_INVOICE_PAYMENT_STATUS_UPDATED",

  //  SALES RETURN EXTENDED ACTIONS
  SALES_RETURN_APPROVED: "SALES_RETURN_APPROVED",
  SALES_RETURN_REJECTED: "SALES_RETURN_REJECTED",
  SALES_RETURN_REVERTED: "SALES_RETURN_REVERTED",

  // ============================================
  //  CUSTOMER MODULE ACTIONS (ADDED)
  // ============================================
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_DELETED: "CUSTOMER_DELETED",
  CUSTOMER_CREDIT_UPDATED: "CUSTOMER_CREDIT_UPDATED",

  //  CUSTOMER CREDIT ACTIONS
  CUSTOMER_CREDIT_CREATED: "CUSTOMER_CREDIT_CREATED",
  CUSTOMER_CREDIT_APPLIED: "CUSTOMER_CREDIT_APPLIED",
  CUSTOMER_CREDIT_EXPIRED: "CUSTOMER_CREDIT_EXPIRED",

  // ============================================
  //  MEDICINE MODULE ACTIONS (ADDED)
  // ============================================
  MEDICINE_CREATED: "MEDICINE_CREATED",
  MEDICINE_UPDATED: "MEDICINE_UPDATED",
  MEDICINE_DELETED: "MEDICINE_DELETED",

  // ============================================
  //  MASTER MEDICINE CATALOG (CADMIN)
  // ============================================
  MASTER_MEDICINE_CREATED: "MASTER_MEDICINE_CREATED",
  MASTER_MEDICINE_UPDATED: "MASTER_MEDICINE_UPDATED",
  MASTER_MEDICINE_DELETED: "MASTER_MEDICINE_DELETED",
  MASTER_MEDICINE_IMAGE_UPLOADED: "MASTER_MEDICINE_IMAGE_UPLOADED",
  MASTER_MEDICINE_IMAGE_DELETED: "MASTER_MEDICINE_IMAGE_DELETED",

  // Mapping actions
  MEDICINE_MATCHED_TO_VARIANT: "MEDICINE_MATCHED_TO_VARIANT",
  MEDICINE_MATCH_ACCEPTED: "MEDICINE_MATCH_ACCEPTED",
  MEDICINE_MATCH_REJECTED: "MEDICINE_MATCH_REJECTED",
  MEDICINE_UNLINKED: "MEDICINE_UNLINKED",
  UNMAPPED_MEDICINES_IGNORED: "UNMAPPED_MEDICINES_IGNORED",
  MEDICINE_RESUBMITTED_FOR_REVIEW: "MEDICINE_RESUBMITTED_FOR_REVIEW",
  MEDICINE_UNIGNORED: "MEDICINE_UNIGNORED",

  // ============================================
  //  SUPPLIER MODULE ACTIONS (ADDED)
  // ============================================
  SUPPLIER_CREATED: "SUPPLIER_CREATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  SUPPLIER_DELETED: "SUPPLIER_DELETED",

  // ============================================
  //  INVENTORY MODULE ACTIONS (ADDED)
  // ============================================
  STOCK_ADJUSTMENT_CREATED: "STOCK_ADJUSTMENT_CREATED",
  STOCK_ADJUSTMENT_APPROVED: "STOCK_ADJUSTMENT_APPROVED",
  STOCK_MOVEMENT_RECORDED: "STOCK_MOVEMENT_RECORDED",
});

/**
 * Set for O(1) validation lookup
 */
export const VALID_ACTIONS = new Set(Object.values(AuditAction));

/**
 * Validate if an action string is valid
 * @param {string} action
 * @returns {boolean}
 */
export function isValidAction(action) {
  return VALID_ACTIONS.has(action);
}
